### ISSUE TITLE
Copy path - symbol's value as variable is void: $dir

### ISSUE THREAD

**Issue by samspo** [ShingoFukuyama/helm-recentd#1]
Hi Shingo,

The ability to choose where to open the directory in finder is very useful. However, on my system (Mac OSX), it is not possible to copy the path. It tells me : 

```
symbol's value as variable is void: $dir
```

Thank you for you nice package

**Comment by ShingoFukuyama** [comment]
Hi samspo,

Thank you for the issue. I didn't notice the error, but now it's fixed!
